# Generated by Django 3.0.3 on 2020-02-18 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0005_auto_20200218_2315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='institution',
        ),
        migrations.AddField(
            model_name='donation',
            name='institution',
            field=models.ForeignKey(default=15, on_delete=django.db.models.deletion.PROTECT, related_name='donations', to='donation.Institution'),
            preserve_default=False,
        ),
    ]
